name: Create Pull Request from Staging Tag

on:
  push:
    tags:
    - 'stg-*'

permissions:
  contents: write

jobs:
  start:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Date from Tag name
        id: name
        run: |
          echo "name=$(echo ${GITHUB_REF##*stg-})" >> "$GITHUB_OUTPUT"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Check Pull Request
        id: check
        run: |
          echo "exists=$(gh pr list --state=open --base=production --head=release/2024-12-12 --repo=$GITHUB_REPOSITORY --json 'id' --jq '.[] | length')" >> "$GITHUB_OUTPUT"
      - name: Create Release Branch
        id: branch
        if: steps.check.outputs.exists == ''
        run: |
          BRANCH="release/${{ steps.name.outputs.name }}"
          git checkout -b "$BRANCH"
          git push origin "$BRANCH"
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        id: pr
        if: steps.check.outputs.exists == ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ steps.branch.outputs.branch }}
        run: |
          gh pr create --base="production" --head="$HEAD_BRANCH" --fill-verbose --repo="$GITHUB_REPOSITORY"
