name: Create Pull Request from Staging Tag

on:
  push:
    tags:
    - 'stg-*'

permissions:
  contents: write
  pull-requests: write

env:
  BASE_BRANCH: production

jobs:
  start:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Date from Tag name
        id: name
        run: |
          TMP="${GITHUB_REF##*stg-}"
          echo "name=$(echo ${TMP//-/})" >> "$GITHUB_OUTPUT"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Check Pull Request
        id: check
        run: |
          echo "exists=$(gh pr list --state=open --base=$BASE_BRANCH --head=release/${{ steps.name.outputs.name }} --repo=$GITHUB_REPOSITORY --json 'id' --jq '.[] | length')" >> "$GITHUB_OUTPUT"
      - name: Create Release Branch
        id: branch
        if: steps.check.outputs.exists == ''
        run: |
          BRANCH="release/${{ steps.name.outputs.name }}"
          git checkout -b "$BRANCH"
          git push origin "$BRANCH"
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
      - name: Check Repository
        run: |
          git log --first-parent --oneline origin/$BASE_BRANCH
          git log --first-parent --oneline origin/$HEAD_BRANCH
      - name: Create Pull Request
        id: pr
        if: steps.check.outputs.exists == ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ steps.branch.outputs.branch }}
          TITLE: "Release/${{ steps.name.outputs.name }}"
        run: |
          BODY=""
          COMMITS=$(git log --first-parent --oneline origin/$BASE_BRANCH..origin/$HEAD_BRANCH)
          COMMITS_TEXT=$(echo $COMMITS | cut -d " " -f2-)
          echo $COMMITS_TEXT | while read line; do
            if [[ $line == "Merge pull request #"* ]]; then
              edit_text=$(echo $line | sed -e "s/Merge pull request #\([0-9]*\) from .*/#\1/")
              BODY=$(echo "$BODY\n- $edit_text")
            else
             BODY=$(echo "$BODY\n- $line")
            fi
          done
          if [[ -n "$BODY" ]]; then
            BODY=$(echo "### リリース内容\n$BODY")
          fi
          echo "---------"
          echo $BODY
          echo "---------"
          gh pr create --base="$BASE_BRANCH" --head="$HEAD_BRANCH" --title="$TITLE" --body="$BODY" --repo="$GITHUB_REPOSITORY"
