name: Release Draft

on:
  pull_request:
    branches:
      - production
    types: [closed]

permissions:
  contents: write

jobs:
  start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Get Current Date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Create Release Name
        id: name
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NAME="prod-${{ steps.date.outputs.date }}"
          COUNT=$(gh release list --repo="$GITHUB_REPOSITORY" --json name --jq "map(select(.name | contains(\"$NAME\"))) | length")
          if [ $COUNT -gt 0 ]; then
            while gh release view "$NAME-$COUNT" --repo="$GITHUB_REPOSITORY" --json name --jq '.name' &>/dev/null; do
              COUNT=$((COUNT + 1))
            done
            echo "name=prod-${{ steps.date.outputs.date }}-$COUNT" >> "$GITHUB_OUTPUT"
          else
            echo "name=prod-${{ steps.date.outputs.date }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Draft Release
        id: create-draft-release
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.name.outputs.name }}
          RELEASE_NAME: ${{ steps.name.outputs.name }}
        run: |
          gh release create "$TAG_NAME" --target "production" --repo="$GITHUB_REPOSITORY" --title="$RELEASE_NAME" --generate-notes --draft
      - name: Exclude Releases
        id: exclude-releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUSION_DAY: 3
        # JQ_QUERY は ドラフトで createdAt がEXCLUSION_DAY日超えているものを抽出する Mac と Linux での互換性を考慮
        run: |
          if date -v -1d > /dev/null 2>&1; then
            EXCLUSION_DAY_AGO_ISO8601=$(date -v -$EXCLUSION_DAYd -u +"%Y-%m-%dT%H:%M:%SZ")
          else
            EXCLUSION_DAY_AGO_ISO8601=$(date -d "$EXCLUSION_DAY day ago" -u +"%Y-%m-%dT%H:%M:%SZ")
          fi
          JQ_QUERY="[.[] | select(.isDraft and .createdAt < \"$EXCLUSION_DAY_AGO_ISO8601\")] | sort_by(.createdAt)[:-1]"
          RELEASE_LIST=$(gh release list --repo="$GITHUB_REPOSITORY" --json isDraft,name,tagName,createdAt -q "$JQ_QUERY")
          if [ -n "$RELEASE_LIST" ]; then
            for release in $(echo "$RELEASE_LIST" | jq -r '.[].tagName'); do
              gh release delete --yes --repo="$GITHUB_REPOSITORY" "$release"
            done
          else
            echo "No releases to exclude."
          fi
