name: Relase Draft

on:
  pull_request:
    branches:
      - production
    types: [closed]

permissions:
  contents: write

jobs:
  start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Create Release Name
        id: name
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESULT=$(gh release list  --repo="$GITHUB_REPOSITORY" --json name --jq '.[] |.name') 
          NAME="prod-${{ steps.date.outputs.date }}"
          COUNT=$(echo $RESULT | grep -c \"$NAME\")
          if [ $COUNT -gt 0 ]; then
            echo "name=prod-${{ steps.date.outputs.dae }}-$COUNT" >> "$GITHUB_OUTPUT"
          else
            echo "name=prod-${{ steps.date.outputs.date }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Draft Release
        id: create-draft-release
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.name.outputs.name }}
          RELEASE_NAME: ${{ steps.name.outputs.name }}
        run: |
          gh release create "$TAG_NAME" --repo="$GITHUB_REPOSITORY" --title="$RELEASE_NAME" --generate-notes --draft
