name: Relase Draft

on:
  pull_request:
    branches:
      - production
    types: [closed]

permissions:
  contents: write

jobs:
  start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Release name exists?
        id: count
        run: |
          RESULT=$(gh release list --json name --jq '.[] |.name') 
          echo $RESULT | grep -c "prod-2024-12-12" >> "$GITHUB_OUTPUT"
      - name: Create Draft Release
        id: create-draft-release
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: prod-${{ steps.date.outputs.date }}${{ steps.count.outputs.count > 0 && '-'steps.count.outputs.count || '' }}
          RELEASE_NAME: prod-${{ steps.date.outputs.date }}${{ steps.count.outputs.count > 0 && '-'steps.count.outputs.count || '' }}
        run: |
          gh release create "$TAG_NAME" --repo="$GITHUB_REPOSITORY" --title="$RELEASE_NAME" --generate-notes --draft
