name: Release Draft

on:
  pull_request:
    branches:
      - production
    types: [closed]

permissions:
  contents: write

jobs:
  start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Get Current Date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Create Release Name
        id: name
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NAME="prod-${{ steps.date.outputs.date }}"
          COUNT=$(gh release list --repo="$GITHUB_REPOSITORY" --json name --jq "map(select(.name | contains(\"$NAME\"))) | length")
          if [ $COUNT -gt 0 ]; then
            echo "name=prod-${{ steps.date.outputs.date }}-$COUNT" >> "$GITHUB_OUTPUT"
          else
            echo "name=prod-${{ steps.date.outputs.date }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Draft Release
        id: create-draft-release
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.name.outputs.name }}
          RELEASE_NAME: ${{ steps.name.outputs.name }}
        run: |
          gh release create "$TAG_NAME" --target "production" --repo="$GITHUB_REPOSITORY" --title="$RELEASE_NAME" --generate-notes --draft
      - name: Release List
        id: release-list
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release list --repo="$GITHUB_REPOSITORY" --json isDraft,name,createdAt -q '[.[] | select(.isDraft)] | sort_by(.createdAt)'
