name: Relase Drafter

on:
  # push:
  #   branches:
  #     - production
  pull_request:
    branches:
      - production
    types: [closed]

permissions:
  contents: write

jobs:
  start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Create Draft Release
        id: create-draft-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.base_ref }}
        run: |
          gh release create "prod-${tag##*/}" \ 
              --repo "$GITHUB_REPOSITORY" \
              --title="prod-${tag##*/}" \
              --generate-notes \
              --draft
