name: Relase Drafter

on:
  # push:
  #   branches:
  #     - production
  pull_request:
    branches:
      - production
    types: [closed]

permissions:
  contents: write

jobs:
  start:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Draft Release
        id: create-draft-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: prod-${{ steps.date.outputs.date }}
          RELEASE_NAME: prod-${{ steps.date.outputs.date }}
        run: |
          gh release create "$TAG_NAME" \ 
              --repo "$GITHUB_REPOSITORY" \
              --title="$RELEASE_NAME" \
              --generate-notes \
              --draft
